// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3G8CGC-qf9_ZZM_ecDLCdfMgQO6Tay1g',
    appId: '1:31535120185:web:d8024fd4912c3b28a2b2e8',
    messagingSenderId: '31535120185',
    projectId: 'gageguru-dfd43',
    authDomain: 'gageguru-dfd43.firebaseapp.com',
    storageBucket: 'gageguru-dfd43.appspot.com',
    measurementId: 'G-RZN6LGJ9XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdiNvxg7yjPpoMiRHNJFBz846ku71t7TU',
    appId: '1:31535120185:android:bc5e23c40a3f3325a2b2e8',
    messagingSenderId: '31535120185',
    projectId: 'gageguru-dfd43',
    storageBucket: 'gageguru-dfd43.appspot.com',
  );

}